name: MicaForEveryone

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      ZIP_FILE: MicaForEveryone-${{ matrix.platform }}-${{ matrix.configuration }}.zip
      MSIX_FILE: MicaForEveryone-${{ matrix.platform }}-${{ matrix.configuration }}.msixbundle
      RELEASE_DIR: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build the application
      run: msbuild MicaForEveryone\MicaForEveryone.csproj /restore /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:ReleaseDirectory=..\$env:RELEASE_DIR /p:ZipName=$env:ZIP_FILE /t:ReleaseZip
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
    - name: Upload Release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ZIP_FILE }}
        path: ${{ env.RELEASE_DIR }}\${{ env.ZIP_FILE }}
        if-no-files-found: error
    - name: Build Installer
      run: '${env:ProgramFiles(x86)}\Inno Setup 6\iscc.exe' Installer.iss
      env:
        Source: MicaForEveryone\bin\${{ matrix.platform }}\${{ matrix.configuration }}\netcoreapp3.1
    - name: Upload Installer
      uses: actions/upload-artifact@v2
      with:
        path: Output\
        if-no-files-found: error
    - name: Clean MicaForEveryone.UI
      run: msbuild MicaForEveryone.sln /p:Configuration=$env:Configuration /p:Platform=$env:Platform /t:Clean
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
    - name: Package as MSIX
      run: msbuild MicaForEveryone.Package\MicaForEveryone.Package.wapproj /restore /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:AppxBundlePlatforms=$env:Platform /p:ErrorOnDuplicatePublishOutputFiles=false /p:ReleaseDirectory=..\$env:RELEASE_DIR /p:MsixName=$env:MSIX_FILE /t:ReleaseMsix
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
    - name: Sign Package
      run: SignTool sign /fd SHA256 /a /f MicaForEveryone.pfx /p ${{ secrets.KEY_PASSWORD }} $env:RELEASE_DIR\$env:MSIX_FILE
    - name: Upload MSIX
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.MSIX_FILE }}
        path: ${{ env.RELEASE_DIR }}\${{ env.MSIX_FILE }}
        if-no-files-found: error